### ISSUE TITLE
怎么切换日语版本？

### ISSUE THREAD

**Issue by 573462273** [Garry050/SSPanel-Uim-JPN#2]
**我确认我已经阅读了** (使用 "x" 选择)

- [ ] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [ ] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [ ] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

**Comment by Garry050** [comment]
注意：此版本尚**未完全**翻译。
有一页（404，TOS等）写了我的服务名。请改变你自己。

切换日语版
$ cd /www/wwwroot/你的文件夹名
$ git remote add jpn https://github.com/Garry050/SSPanel-Uim-JPN.git
$ git fetch jpn
$ git reset --hard jpn/master
$ git pull

版本升级
$ git fetch --all
$ git reset --hard **jpn**/master
$ git pull

**Comment by Garry050** [comment]
also, I don't support anything. so...
即使出现了问题，他们都要**自我负责**
